### ISSUE TITLE
discoverability: Github repo description and topics/tags

### ISSUE THREAD

**Issue by nsajko** [JuliaArrays/FixedSizeArrays.jl#31]
This repo should have a description, for example:

> Fixed-size multidimensional arrays. An `Array`-like type with less indirection at the cost of resizing capability.

Some Github topics would probably also be good, for example `julia` and `arrays`.

AFAIK JuliaHub records these when registering packages and uses it to improve JuliaHub search. Of course they should also help with Github search.

**Comment by giordano** [comment]
Done!
